project:
  type: book
  output-dir: docs

execute:
  freeze: auto

lang: pt 

book:
  title: "Dados e Indicadores de Interesse para a Saúde Pública"
  author: "Raphael de Freitas Saldanha"
  isbn: ""
  date: today
  search: true
  # downloads: [pdf, epub]
  google-analytics: 
    tracking-id: G-2M7VLSRDCB
    anonymize-ip: false
  chapters:
    - index.qmd
    - intro.qmd
    - indi.qmd
    - harmo.qmd
    - socio.qmd # Sociodemográficos
    - ambi.qmd  # Ambientais (cobertura e uso do solo)
    - clima.qmd # Climáticos e atmosféricos
    - inter.qmd # Dados da internet e redes sociais
    - referencias.qmd
  # appendices: 
    # - malhas.qmd # Malhas territoriais, DTB

bibliography: references.bib
csl: abnt.csl

format:
  html:
    theme:
      light: journal
      dark: darkly
  #pdf:
  #  documentclass: scrreprt
  #epub: 
  #  toc: true
